// GENERATED from the contents of public/brands/ — do not hand-edit.
// Regenerated by scanning folders: folder name -> brand name (hyphens -> spaces, uppercased),
// files in filename order -> products. Empty folders are skipped.
export const IMAGE_BASE = "public/brands/";

function brand(slug, index, files, displayName) {
  const name = displayName || slug.replace(/-/g, " ").toUpperCase();
  return {
    id: slug,
    name,
    index,
    products: files.map((f, i) => ({
      id: slug + "-" + f.replace(/\.[a-z]+$/i, ""),
      label: name + " \u2014 " + String(i + 1).padStart(2, "0"),
      image: slug + "/" + f
    }))
  };
}

export const brands = [
  brand("misraa", "01", ["01.jpg", "02.jpg", "03.jpg", "04.jpg"]),
  brand("day-age", "02", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg"], "DAY & AGE"),
  brand("hindostan-archives", "03", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg"]),
  brand("aaram-viram", "04", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"]),
  brand("noborders", "05", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg"], "NO BORDERS"),
  brand("cord", "06", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg"]),
  brand("kosch", "07", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg"]),
  brand("kissa-goi", "08", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"]),
  brand("salooka", "09", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg"]),
  brand("saphed-living", "10", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg"]),
  brand("projekt-draw", "11", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg"]),
  brand("margn", "12", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg"]),
  brand("insane-shell", "13", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg"]),
  brand("countrymade", "14", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "17.jpg", "18.jpg", "19.jpg", "20.jpg"]),
  brand("three", "15", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg"]),
  brand("triune", "16", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg"]),
  brand("ludic-life", "17", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"]),
  brand("knn-calcutta", "18", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"]),
  brand("oddnoteven", "19", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg"]),
  brand("kilogram", "20", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"]),
  brand("lab88", "21", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg"]),
  brand("chapter2", "22", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"]),
  brand("our-own-pace", "23", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg"]),
  brand("acru", "24", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg"]),
  brand("senses", "25", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg"]),
  brand("yur", "26", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg"]),
  brand("warping-theories", "27", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg"]),
  brand("wasted-wrld", "28", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg"]),
  brand("towards", "29", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg"]),
  brand("the-draft-xx", "30", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg"]),
  brand("nocap", "31", ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg"], "NO CAP"),
];
